[2024-05-05T05:52:38.422+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T05:52:38.434+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.feed_to_bigq manual__2024-05-05T05:49:01.286722+00:00 [queued]>
[2024-05-05T05:52:38.440+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.feed_to_bigq manual__2024-05-05T05:49:01.286722+00:00 [queued]>
[2024-05-05T05:52:38.441+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-05T05:52:38.460+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): feed_to_bigq> on 2024-05-05 05:49:01.286722+00:00
[2024-05-05T05:52:38.472+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'feed_to_bigq', 'manual__2024-05-05T05:49:01.286722+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmps80xw5en']
[2024-05-05T05:52:38.473+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask feed_to_bigq
[2024-05-05T05:52:38.484+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=52777) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T05:52:38.484+0000] {standard_task_runner.py:63} INFO - Started process 52794 to run task
[2024-05-05T05:52:38.521+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.feed_to_bigq manual__2024-05-05T05:49:01.286722+00:00 [running]> on host 5bc5768c5236
[2024-05-05T05:52:38.605+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='feed_to_bigq' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T05:49:01.286722+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T05:49:01.286722+00:00'
[2024-05-05T05:52:38.606+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T05:52:38.607+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T05:52:38.607+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 86, in _feed_to_bigq
    service_account_info = json.load(open(keyfile))
                                     ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'credentials/admin.json'
[2024-05-05T05:52:38.614+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=feed_to_bigq, execution_date=20240505T054901, start_date=20240505T055238, end_date=20240505T055238
[2024-05-05T05:52:38.628+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task feed_to_bigq ([Errno 2] No such file or directory: 'credentials/admin.json'; 52794)
[2024-05-05T05:52:38.658+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T05:52:38.676+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T05:52:38.685+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
