[2024-05-05T05:15:09.961+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T05:15:09.999+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.load_csv_delimiter scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T05:15:10.007+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.load_csv_delimiter scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-05T05:15:10.007+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-05T05:15:10.023+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): load_csv_delimiter> on 2024-05-04 00:00:00+00:00
[2024-05-05T05:15:10.033+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'load_csv_delimiter', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpnxb_jcia']
[2024-05-05T05:15:10.035+0000] {standard_task_runner.py:91} INFO - Job 72: Subtask load_csv_delimiter
[2024-05-05T05:15:10.039+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=32611) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T05:15:10.040+0000] {standard_task_runner.py:63} INFO - Started process 32618 to run task
[2024-05-05T05:15:10.076+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.load_csv_delimiter scheduled__2024-05-04T00:00:00+00:00 [running]> on host 5bc5768c5236
[2024-05-05T05:15:10.164+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='load_csv_delimiter' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-05-05T05:15:10.166+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T05:15:10.172+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-05T05:15:10.176+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-05-05T05:15:10.177+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-05-05T05:15:10.223+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'upbeat-task-421414', 'datasetId': 'pm25', 'tableId': 'pm25_data'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://dw-projec-swu-ds525/all_data.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': '\t', 'quote': '', 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-05-05T05:15:10.224+0000] {bigquery.py:1613} INFO - Inserting job ***_sample_load_csv_delimiter_2024_05_04T00_00_00_00_00_4f8818730dac7ae92fbf1995f23505a6
[2024-05-05T05:15:10.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T05:15:10.660+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 384, in execute
    job: BigQueryJob | UnknownJob = self._submit_job(self.hook, job_id)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 306, in _submit_job
    return hook.insert_job(
           ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1616, in insert_job
    job_api_repr._begin()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/upbeat-task-421414/jobs?prettyPrint=false: Access Denied: Project upbeat-task-421414: User does not have bigquery.jobs.create permission in project upbeat-task-421414.
[2024-05-05T05:15:10.672+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=load_csv_delimiter, execution_date=20240504T000000, start_date=20240505T051510, end_date=20240505T051510
[2024-05-05T05:15:10.700+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 72 for task load_csv_delimiter (403 POST https://bigquery.googleapis.com/bigquery/v2/projects/upbeat-task-421414/jobs?prettyPrint=false: Access Denied: Project upbeat-task-421414: User does not have bigquery.jobs.create permission in project upbeat-task-421414.; 32618)
[2024-05-05T05:15:10.734+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T05:15:10.764+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T05:15:10.772+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
