[2024-05-05T09:07:29.235+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T09:07:29.247+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.clean_df manual__2024-05-05T09:04:09.920819+00:00 [queued]>
[2024-05-05T09:07:29.253+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.clean_df manual__2024-05-05T09:04:09.920819+00:00 [queued]>
[2024-05-05T09:07:29.253+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-05-05T09:07:29.268+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clean_df> on 2024-05-05 09:04:09.920819+00:00
[2024-05-05T09:07:29.278+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=47561) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T09:07:29.278+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'clean_df', 'manual__2024-05-05T09:04:09.920819+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp81d6k5wf']
[2024-05-05T09:07:29.279+0000] {standard_task_runner.py:63} INFO - Started process 47583 to run task
[2024-05-05T09:07:29.279+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask clean_df
[2024-05-05T09:07:29.328+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.clean_df manual__2024-05-05T09:04:09.920819+00:00 [running]> on host 5bc5768c5236
[2024-05-05T09:07:29.408+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='clean_df' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T09:04:09.920819+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T09:04:09.920819+00:00'
[2024-05-05T09:07:29.409+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T09:07:29.425+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/my_dag.py:80 FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
[2024-05-05T09:07:38.323+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T09:07:38.323+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 81, in _clean_df
    df_all.set_index(['datetime','name_en'], inplace=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5870, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['name_en'] are in the columns"
[2024-05-05T09:07:38.332+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=clean_df, execution_date=20240505T090409, start_date=20240505T090729, end_date=20240505T090738
[2024-05-05T09:07:38.378+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 174 for task clean_df ("None of ['name_en'] are in the columns"; 47583)
[2024-05-05T09:07:38.425+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T09:07:38.459+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T09:07:38.471+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
