[2024-05-05T10:12:42.073+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T10:12:42.085+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.transform_to_db manual__2024-05-05T10:06:43.455582+00:00 [queued]>
[2024-05-05T10:12:42.092+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.transform_to_db manual__2024-05-05T10:06:43.455582+00:00 [queued]>
[2024-05-05T10:12:42.092+0000] {taskinstance.py:2303} INFO - Starting attempt 5 of 5
[2024-05-05T10:12:42.108+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_to_db> on 2024-05-05 10:06:43.455582+00:00
[2024-05-05T10:12:42.118+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=82817) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T10:12:42.118+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'transform_to_db', 'manual__2024-05-05T10:06:43.455582+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp996x5tte']
[2024-05-05T10:12:42.119+0000] {standard_task_runner.py:63} INFO - Started process 82829 to run task
[2024-05-05T10:12:42.119+0000] {standard_task_runner.py:91} INFO - Job 200: Subtask transform_to_db
[2024-05-05T10:12:42.159+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.transform_to_db manual__2024-05-05T10:06:43.455582+00:00 [running]> on host 5bc5768c5236
[2024-05-05T10:12:42.292+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='transform_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T10:06:43.455582+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T10:06:43.455582+00:00'
[2024-05-05T10:12:42.294+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T10:12:42.763+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/my_dag.py:128 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-05-05T10:12:49.074+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T10:12:49.075+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 138, in _transform_to_db
    client.load_table_from_dataframe(df_need, table_).result()
                                              ^^^^^^
NameError: name 'table_' is not defined
[2024-05-05T10:12:49.084+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=transform_to_db, execution_date=20240505T100643, start_date=20240505T101242, end_date=20240505T101249
[2024-05-05T10:12:49.098+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 200 for task transform_to_db (name 'table_' is not defined; 82829)
[2024-05-05T10:12:49.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T10:12:49.134+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T10:12:49.143+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
