[2024-05-05T08:52:26.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T08:52:26.482+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sample.feed_to_bigq manual__2024-05-05T08:23:10.311042+00:00 [queued]>
[2024-05-05T08:52:26.489+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sample.feed_to_bigq manual__2024-05-05T08:23:10.311042+00:00 [queued]>
[2024-05-05T08:52:26.489+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-05T08:52:26.505+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): feed_to_bigq> on 2024-05-05 08:23:10.311042+00:00
[2024-05-05T08:52:26.515+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=39470) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-05T08:52:26.514+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sample', 'feed_to_bigq', 'manual__2024-05-05T08:23:10.311042+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpgvjs2ejs']
[2024-05-05T08:52:26.516+0000] {standard_task_runner.py:63} INFO - Started process 39491 to run task
[2024-05-05T08:52:26.516+0000] {standard_task_runner.py:91} INFO - Job 164: Subtask feed_to_bigq
[2024-05-05T08:52:26.555+0000] {task_command.py:426} INFO - Running <TaskInstance: sample.feed_to_bigq manual__2024-05-05T08:23:10.311042+00:00 [running]> on host 5bc5768c5236
[2024-05-05T08:52:26.633+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sample' AIRFLOW_CTX_TASK_ID='feed_to_bigq' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T08:23:10.311042+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T08:23:10.311042+00:00'
[2024-05-05T08:52:26.634+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T08:52:26.835+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T08:52:26.835+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 103, in _feed_to_bigq
    load_job = client.load_table_from_uri(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2475, in load_table_from_uri
    load_job._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 740, in _begin
    api_response = client._call_api(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 831, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/upbeat-task-421414/jobs?prettyPrint=false: Only CSV imports may specify leading rows to skip.
[2024-05-05T08:52:26.877+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sample, task_id=feed_to_bigq, execution_date=20240505T082310, start_date=20240505T085226, end_date=20240505T085226
[2024-05-05T08:52:26.891+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 164 for task feed_to_bigq (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/upbeat-task-421414/jobs?prettyPrint=false: Only CSV imports may specify leading rows to skip.; 39491)
[2024-05-05T08:52:26.936+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T08:52:26.960+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T08:52:26.968+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
